micronaut:
  application:
    name: test-course-template
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: supaDupaSecretThatNobodyWillKnow
    endpoints:
      login:
        enabled: false

db:
  users:
    filename: users.txt
  sessions:
    filename: sessions.txt
